module.exports = [
    { name: "Accountant" },
    { name: "Accounting Manager" },
    { name: "Actuarial Analyst" },
    { name: "Administrative Assistant" },
    { name: "AI Engineer" },
    { name: "Analytics Manager" },
    { name: "Application Developer" },
    { name: "Art Director" },
    { name: "Asset Manager" },
    { name: "Audit Manager" },
    { name: "Backend Developer" },
    { name: "Bank Teller" },
    { name: "Benefits Coordinator" },
    { name: "Biomedical Engineer" },
    { name: "Brand Manager" },
    { name: "Business Analyst" },
    { name: "Business Development Manager" },
    { name: "CFO" },
    { name: "Chief Marketing Officer" },
    { name: "Chief Operating Officer" },
    { name: "Civil Engineer" },
    { name: "Cloud Engineer" },
    { name: "Compliance Officer" },
    { name: "Content Strategist" },
    { name: "Copywriter" },
    { name: "Creative Director" },
    { name: "Customer Success Manager" },
    { name: "Cybersecurity Analyst" },
    { name: "Data Analyst" },
    { name: "Data Engineer" },
    { name: "Data Scientist" },
    { name: "Database Administrator" },
    { name: "Dentist" },
    { name: "DevOps Engineer" },
    { name: "Digital Marketing Specialist" },
    { name: "Doctor" },
    { name: "Economist" },
    { name: "Electrical Engineer" },
    { name: "Elementary School Teacher" },
    { name: "Embedded Systems Engineer" },
    { name: "Environmental Engineer" },
    { name: "Event Coordinator" },
    { name: "Executive Assistant" },
    { name: "Facilities Manager" },
    { name: "Financial Analyst" },
    { name: "Financial Planner" },
    { name: "Fleet Manager" },
    { name: "Frontend Developer" },
    { name: "Full Stack Developer" },
    { name: "General Counsel" },
    { name: "Graphic Designer" },
    { name: "Healthcare Administrator" },
    { name: "Help Desk Technician" },
    { name: "Human Resources Manager" },
    { name: "Industrial Designer" },
    { name: "Industrial Engineer" },
    { name: "Information Security Analyst" },
    { name: "Infrastructure Engineer" },
    { name: "Insurance Agent" },
    { name: "Interior Designer" },
    { name: "Investment Banker" },
    { name: "IT Project Manager" },
    { name: "Java Developer" },
    { name: "Lawyer" },
    { name: "Legal Assistant" },
    { name: "Logistics Coordinator" },
    { name: "Machine Learning Engineer" },
    { name: "Maintenance Technician" },
    { name: "Manufacturing Engineer" },
    { name: "Marketing Coordinator" },
    { name: "Marketing Manager" },
    { name: "Mechanical Engineer" },
    { name: "Medical Assistant" },
    { name: "Mobile App Developer" },
    { name: "Network Administrator" },
    { name: "Network Engineer" },
    { name: "Nurse Practitioner" },
    { name: "Occupational Therapist" },
    { name: "Office Manager" },
    { name: "Operations Manager" },
    { name: "Paralegal" },
    { name: "Payroll Specialist" },
    { name: "Pharmacist" },
    { name: "Physician" },
    { name: "Physician Assistant" },
    { name: "Product Designer" },
    { name: "Product Manager" },
    { name: "Production Manager" },
    { name: "Project Coordinator" },
    { name: "Project Manager" },
    { name: "Public Relations Specialist" },
    { name: "Quality Assurance Engineer" },
    { name: "Quality Control Inspector" },
    { name: "Recruiter" },
    { name: "Research Scientist" },
    { name: "Risk Manager" },
    { name: "Sales Manager" },
    { name: "Sales Representative" },
    { name: "Scrum Master" },
    { name: "SEO Specialist" },
    { name: "Social Media Manager" },
    { name: "Software Architect" },
    { name: "Software Developer" },
    { name: "Software Engineer" },
    { name: "Solutions Architect" },
    { name: "Supply Chain Manager" },
    { name: "Systems Administrator" },
    { name: "Systems Analyst" },
    { name: "Tax Advisor" },
    { name: "Teacher" },
    { name: "Technical Writer" },
    { name: "UI/UX Designer" },
    { name: "Veterinarian" },
    { name: "Video Producer" },
    { name: "Warehouse Manager" },
    { name: "Web Developer" },
    { name: "Web Designer" },
    { name: "Wellness Coach" }
];
