module.exports = [
    { name: 'JavaScript' },
    { name: 'TypeScript' },
    { name: 'ES6' },
    { name: 'Node.js' },
    { name: 'Express.js' },
    { name: 'NestJS' },
    { name: 'Angular' },
    { name: 'React' },
    { name: 'Vue.js' },
    { name: 'Next.js' },
    { name: 'Nuxt.js' },
    { name: 'Svelte' },
    { name: 'Gatsby' },
    { name: 'jQuery' },
    { name: 'Backbone.js' },
    { name: 'Ember.js' },
    { name: 'Meteor.js' },
    { name: 'Electron' },
    { name: 'Webpack' },
    { name: 'Parcel' },
    { name: 'Grunt' },
    { name: 'Gulp' },
    { name: 'Rollup' },
    { name: 'Babel' },
    { name: 'GraphQL' },
    { name: 'Apollo' },
    { name: 'Socket.IO' },
    { name: 'Three.js' },
    { name: 'D3.js' },
    { name: 'RxJS' },
    { name: 'Redux' },
    { name: 'NgRx' },
    { name: 'Vuex' },
    { name: 'MobX' },
    { name: 'React Native' },
    { name: 'Ionic' },
    { name: 'NativeScript' },
    { name: 'Sass' },
    { name: 'LESS' },
    { name: 'Tailwind CSS' },
    { name: 'Bootstrap' },
    { name: 'Material-UI' },
    { name: 'Ant Design' },
    { name: 'Chakra UI' },
    { name: 'Styled Components' },
    { name: 'Emotion' },
    { name: 'Jest' },
    { name: 'Mocha' },
    { name: 'Chai' },
    { name: 'Karma' },
    { name: 'Protractor' },
    { name: 'Cypress' },
    { name: 'Puppeteer' },
    { name: 'Testing Library' },
    { name: 'Storybook' },
    { name: 'ESLint' },
    { name: 'Prettier' },
    { name: 'Vite' },
    { name: 'Swagger' },
    { name: 'Postman' },
    { name: 'REST API' },
    { name: 'GraphQL API' },
    { name: 'JWT (JSON Web Tokens)' },
    { name: 'OAuth' },
    { name: 'Passport.js' },
    { name: 'Firebase' },
    { name: 'MongoDB' },
    { name: 'Mongoose' },
    { name: 'PostgreSQL' },
    { name: 'MySQL' },
    { name: 'SQLite' },
    { name: 'Docker' },
    { name: 'Kubernetes' },
    { name: 'NGINX' },
    { name: 'Heroku' },
    { name: 'Netlify' },
    { name: 'Vercel' },
    { name: 'AWS' },
    { name: 'Azure' },
    { name: 'Google Cloud Platform' },
    { name: 'DigitalOcean' }
];
