module.exports = [
    // General Skills
    { name: "Adaptability" },
    { name: "Attention to Detail" },
    { name: "Analytical Thinking" },
    { name: "Communication" },
    { name: "Conflict Resolution" },
    { name: "Critical Thinking" },
    { name: "Decision Making" },
    { name: "Emotional Intelligence" },
    { name: "Leadership" },
    { name: "Negotiation" },
    { name: "Organizational Skills" },
    { name: "Problem Solving" },
    { name: "Project Management" },
    { name: "Strategic Planning" },
    { name: "Teamwork" },
    { name: "Time Management" },
    { name: "Written Communication" },

    // IT and Technical Skills
    { name: "Agile Methodologies" },
    { name: "API Development" },
    { name: "AWS Cloud" },
    { name: "Backend Development" },
    { name: "Big Data" },
    { name: "Blockchain Development" },
    { name: "Cloud Computing" },
    { name: "Cybersecurity" },
    { name: "Data Analysis" },
    { name: "Data Engineering" },
    { name: "Data Science" },
    { name: "Database Administration" },
    { name: "DevOps" },
    { name: "Frontend Development" },
    { name: "Full Stack Development" },
    { name: "Machine Learning" },
    { name: "Mobile App Development" },
    { name: "Network Administration" },
    { name: "Software Development" },
    { name: "System Administration" },
    { name: "UI/UX Design" },
    { name: "Web Development" },

    // Healthcare Skills
    { name: "Basic Life Support (BLS)" },
    { name: "Clinical Research" },
    { name: "Critical Care Nursing" },
    { name: "First Aid" },
    { name: "Healthcare Administration" },
    { name: "Medical Coding" },
    { name: "Patient Care" },
    { name: "Pharmacology" },
    { name: "Physiotherapy" },
    { name: "Public Health" },
    { name: "Surgical Assistance" },

    // Education and Training Skills
    { name: "Curriculum Design" },
    { name: "E-Learning Development" },
    { name: "Instructional Design" },
    { name: "Lesson Planning" },
    { name: "Public Speaking" },
    { name: "Special Education" },
    { name: "Teaching" },
    { name: "Training and Development" },

    // Finance and Business Skills
    { name: "Accounting" },
    { name: "Auditing" },
    { name: "Budget Management" },
    { name: "Business Analysis" },
    { name: "Financial Modeling" },
    { name: "Investment Analysis" },
    { name: "Market Research" },
    { name: "Payroll Management" },
    { name: "Risk Management" },
    { name: "Sales Strategy" },

    // Logistics and Operations Skills
    { name: "Fleet Management" },
    { name: "Inventory Management" },
    { name: "Logistics Coordination" },
    { name: "Operations Management" },
    { name: "Procurement" },
    { name: "Shipping and Receiving" },
    { name: "Supply Chain Management" },
    { name: "Warehouse Management" },

    // Marketing and Creative Skills
    { name: "Brand Management" },
    { name: "Content Creation" },
    { name: "Content Strategy" },
    { name: "Copywriting" },
    { name: "Digital Marketing" },
    { name: "Event Planning" },
    { name: "Graphic Design" },
    { name: "Market Research" },
    { name: "Photography" },
    { name: "Search Engine Optimization (SEO)" },
    { name: "Social Media Management" },
    { name: "Video Editing" },

    // Trade and Craft Skills
    { name: "Auto Repair" },
    { name: "Carpentry" },
    { name: "Construction Management" },
    { name: "Electrical Installation" },
    { name: "HVAC Maintenance" },
    { name: "Mechanical Engineering" },
    { name: "Plumbing" },
    { name: "Welding" },

    // Miscellaneous Skills
    { name: "Customer Service" },
    { name: "Event Coordination" },
    { name: "Fundraising" },
    { name: "Human Resources Management" },
    { name: "Legal Research" },
    { name: "Research Analysis" },
    { name: "Translation and Localization" },
    { name: "Travel Coordination" }
];
